### ISSUE TITLE
Shorten Model Description to "Neural Prophet"

### ISSUE THREAD

**Issue by mdancho84** [AlbertoAlmuinha/neuralprophet#11]
I'd like to see the name shortened from "Neural Prophet Model Specification" to "Neural Prophet". This will reduce the width of the model printing in the visualizations. I also interpret a model specification is an untrained model, which if interpreted that way is inaccurate. 

https://github.com/AlbertoAlmuinha/neuralprophet/blob/a07bf6b8a1a852d6d5520da66ccebe94b2985154/R/parsnip-neuralprophet.R#L571

**Comment by AlbertoAlmuinha** [comment]
I completely agree with you, the description can lead to confusion and is not adequate. We can change it.
