### ISSUE TITLE
Improvement: Make Future Regressors Default. 

### ISSUE THREAD

**Issue by mdancho84** [AlbertoAlmuinha/neuralprophet#9]
This is a suggestion to make the fitting process more consistent with the `modeltime::prophet_reg()`. What I do is automatically add regressors when the user supplies them. It normally works pretty well. 

The same logic can be applied to `neural_prophet()`. Any columns that aren't labeled "event_" or `lagged_` can be added as "future regressors".

**Comment by AlbertoAlmuinha** [comment]
I agree that this is a good idea. Let's adapt it so that this is the default behavior therefore.

**Comment by AlbertoAlmuinha** [comment]
This should be ok with the commit I made. I would have to do a few tests to verify that everything works as expected but in principle it should be fine now.
